all:
  children:
    # Servidores Linux
    linux_servers:
      hosts:
        server01:
          ansible_host: 192.168.4.10
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    # Servidores Windows
    windows_servers:
      hosts:
        winserver01:
          ansible_host: 192.168.4.90
          ansible_user: dressto\bruno.adm
          ansible_password: Q15vr5gm@!
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
